/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pebbles;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testBlackBagCSV() {
        ClassLoader classLoader = this.getClass().getClassLoader();
        BlackBag bag = BlackBag.fromCSV(classLoader.getResource("test.csv").getFile());
        for (Integer i=1; i <= 100; i++) {
            assertEquals(bag.removeStone(0), i);
        }
    }
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
